### 1. Vectorization

- Vectorization is a technique that allows us to perform operations on entire arrays or matrices instead of looping through each element individually.

- In a vectorized implementation, you can directly compute the dot product without using a for loop. This is done using built-in functions like np.dot() in Python or numpy. 

![Vectorizing logistic regression](https://github.com/user-attachments/assets/2ec0a66d-d450-4d12-936f-02fbb7a1012c)

#### 1.1 More Examples

1. Matrix multiplication
2. Element-wise operartions
3. Mathematical functions

In [13]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized version: " + str(1000*(toc-tic)) + " ms")

Vectorized version: 2.9947757720947266 ms


In [15]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print("For Loop: " + str(1000*(toc-tic)) + " ms")

For Loop: 981.5566539764404 ms



### 2. Vectorizing Logistic Regression

- We stack our training inputs together in a matrix called X, and then we can compute all the Z values at once using a single line of code. 

- Similarly, we can compute all the activation values at once using another line of code. This saves us a lot of time and makes our code much faster.

#### 2.1 Gradient Output

![Logistic regression gradient output](https://github.com/user-attachments/assets/84040576-93ca-4500-93f4-8a91791394dc)

![Logistic regression gradient output2](https://github.com/user-attachments/assets/5f636650-e8e5-4adf-8019-9135a1f107cc)


### 3. Broadcasting in Python

In [16]:

A = np.array([[56.0, 0.0, 4.4, 68.0], 
              [1.2, 104.0, 52.0, 8.0], 
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [17]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [18]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### 4. Normalization

- Normalization often leads to a better performance because gradient descent converges faster after normalization. 
- By normalization we mean changing x to  `𝑥‖𝑥‖`
(dividing each row vector of x by its norm).

`‖𝑥‖=np.linalg.norm(x, axis=1, keepdims=True)=[5/√56]`

In [19]:
x = np.array([[0., 3., 4.],
              [1., 6., 4.]])
x_norm = np.linalg.norm(x,keepdims = True,ord=2, axis = 1)
x /= x_norm
print(x)

[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


#### 2. Vectorizing across multiple examples

![vectorizing across example](https://github.com/user-attachments/assets/e910a67d-e6c4-48fd-baee-3f2ee44ea5c2)

![vectorizing across 2](https://github.com/user-attachments/assets/272c8892-d73f-49b7-829f-5e43a565e438)