### Vectorization

- Vectorization is a technique that allows us to perform operations on entire arrays or matrices instead of looping through each element individually.

- In a vectorized implementation, you can directly compute the dot product without using a for loop. This is done using built-in functions like np.dot() in Python or numpy. 

![Vectorizing logistic regression](https://github.com/user-attachments/assets/2ec0a66d-d450-4d12-936f-02fbb7a1012c)

#### More Examples

1. Matrix multiplication
2. Element-wise operartions
3. Mathematical functions

In [7]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized version: " + str(1000*(toc-tic)) + " ms")

Vectorized version: 1.9998550415039062 ms


In [9]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print("For Loop: " + str(1000*(toc-tic)) + " ms")

For Loop: 546.2851524353027 ms



### Vectorizing Logistic Regression

- We stack our training inputs together in a matrix called X, and then we can compute all the Z values at once using a single line of code. 

- Similarly, we can compute all the activation values at once using another line of code. This saves us a lot of time and makes our code much faster.

#### Gradient Output

![Logistic regression gradient output](https://github.com/user-attachments/assets/84040576-93ca-4500-93f4-8a91791394dc)

![Logistic regression gradient output2](https://github.com/user-attachments/assets/5f636650-e8e5-4adf-8019-9135a1f107cc)


### Broadcasting in Python

In [10]:

A = np.array([[56.0, 0.0, 4.4, 68.0], 
              [1.2, 104.0, 52.0, 8.0], 
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [12]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
